[build]
  publish = "public"
  command = "bundle exec jekyll build"
  
  [[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = '''
    max-age=300,
    must-revalidate'''
    Content-Security-Policy = "default-src https://levay08.github.io https://inspiring-bienenstitch-04c134.netlify.app; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    Permissions-Policy = "geolocation=(), microphone=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
